import type { ProtocolToolManifest } from "../../types.js";

export const PERPS_TOOLS: readonly ProtocolToolManifest[] = [
  {
    toolId: "solana.perps.markets",
    namespace: "solana",
    lifecycle: "active",
    description: "Get perps market stats — SOL/BTC/ETH price, 24h change, volume, high/low.",
    mutating: false,
    params: [],
    exampleParams: {},
  },
  {
    toolId: "solana.perps.positions",
    namespace: "solana",
    lifecycle: "active",
    description: "Get open perps positions + pending limit orders for a wallet.",
    mutating: false,
    params: [
      { key: "address", type: "string", required: true, description: "Wallet address." },
    ],
    exampleParams: { address: "9WzDXwBbmkg8ZTbNMqUxvQRAyrZzDsGYdLVL9zYtAWWM" },
  },
  {
    toolId: "solana.perps.history",
    namespace: "solana",
    lifecycle: "active",
    description: "Get perps trade history — action, side, price, size, PnL, fees.",
    mutating: false,
    params: [
      { key: "address", type: "string", required: true, description: "Wallet address." },
      { key: "asset", type: "string", description: "Filter by asset: SOL, BTC, ETH." },
      { key: "side", type: "string", description: "Filter by side: long, short." },
      { key: "limit", type: "number", description: "Max results." },
    ],
    exampleParams: { address: "9WzDXwBbmkg8ZTbNMqUxvQRAyrZzDsGYdLVL9zYtAWWM", limit: 20 },
  },
  {
    toolId: "solana.perps.open",
    namespace: "solana",
    lifecycle: "active",
    description: "Open a leveraged perps position (market or limit order). Min $10 collateral.",
    mutating: true,
    params: [
      { key: "asset", type: "string", required: true, description: "Asset: SOL, BTC, or ETH." },
      { key: "side", type: "string", required: true, description: "Side: long or short." },
      { key: "amountUsd", type: "number", required: true, description: "Collateral in USD." },
      { key: "leverage", type: "number", description: "Leverage multiplier." },
      { key: "inputToken", type: "string", description: "Collateral token (default: SOL)." },
      { key: "tp", type: "number", description: "Take-profit price (USD)." },
      { key: "sl", type: "number", description: "Stop-loss price (USD)." },
      { key: "limitPrice", type: "number", description: "Limit order trigger price (USD). Mutually exclusive with tp/sl." },
      { key: "slippageBps", type: "number", description: "Max slippage in basis points (default: 200)." },
    ],
    exampleParams: { asset: "SOL", side: "long", amountUsd: 50, leverage: 3 },
  },
  {
    toolId: "solana.perps.close",
    namespace: "solana",
    lifecycle: "active",
    description: "Close a perps position (full or partial).",
    mutating: true,
    params: [
      { key: "positionPubkey", type: "string", required: true, description: "Position public key." },
      { key: "receiveToken", type: "string", description: "Token to receive (default: SOL)." },
      { key: "sizeUsd", type: "number", description: "Partial close amount in USD (omit for full close)." },
      { key: "slippageBps", type: "number", description: "Max slippage in basis points." },
    ],
    exampleParams: { positionPubkey: "Abc123..." },
  },
  {
    toolId: "solana.perps.closeAll",
    namespace: "solana",
    lifecycle: "active",
    description: "Close all open perps positions.",
    mutating: true,
    params: [],
    exampleParams: {},
  },
  {
    toolId: "solana.perps.tpsl",
    namespace: "solana",
    lifecycle: "active",
    description: "Set take-profit and/or stop-loss on an open perps position.",
    mutating: true,
    params: [
      { key: "positionPubkey", type: "string", required: true, description: "Position public key." },
      { key: "tp", type: "number", description: "Take-profit price (USD)." },
      { key: "sl", type: "number", description: "Stop-loss price (USD)." },
      { key: "receiveToken", type: "string", description: "Token to receive (default: SOL)." },
    ],
    exampleParams: { positionPubkey: "Abc123...", tp: 200, sl: 80 },
  },
  {
    toolId: "solana.perps.cancelLimitOrder",
    namespace: "solana",
    lifecycle: "active",
    description: "Cancel a pending perps limit order.",
    mutating: true,
    params: [
      { key: "positionRequestPubkey", type: "string", required: true, description: "Limit order request public key." },
    ],
    exampleParams: { positionRequestPubkey: "Abc123..." },
  },
  {
    toolId: "solana.perps.updateLimitOrder",
    namespace: "solana",
    lifecycle: "active",
    description: "Update trigger price on an existing perps limit order.",
    mutating: true,
    params: [
      { key: "positionRequestPubkey", type: "string", required: true, description: "Limit order request public key." },
      { key: "triggerPrice", type: "number", required: true, description: "New trigger price in USD." },
    ],
    exampleParams: { positionRequestPubkey: "Abc123...", triggerPrice: 150 },
  },
  {
    toolId: "solana.perps.cancelTpsl",
    namespace: "solana",
    lifecycle: "active",
    description: "Cancel a take-profit or stop-loss order on a perps position.",
    mutating: true,
    params: [
      { key: "positionRequestPubkey", type: "string", required: true, description: "TP/SL request public key." },
    ],
    exampleParams: { positionRequestPubkey: "Abc123..." },
  },
  {
    toolId: "solana.perps.updateTpsl",
    namespace: "solana",
    lifecycle: "active",
    description: "Update trigger price on an existing TP/SL order.",
    mutating: true,
    params: [
      { key: "positionRequestPubkey", type: "string", required: true, description: "TP/SL request public key." },
      { key: "triggerPrice", type: "number", required: true, description: "New trigger price in USD." },
    ],
    exampleParams: { positionRequestPubkey: "Abc123...", triggerPrice: 180 },
  },
];
