export const CHAINSCAN_DEFAULTS = {
  BASE_URL: "https://chainscan.0g.ai/open",
  API_PATH: "/api",
  TIMEOUT_MS: 10_000,
  RATE_LIMIT_PER_SEC: 4,
  MAX_CONCURRENT: 3,
  MAX_RETRIES: 2,
  MAX_BATCH_DECODE: 10,
  MAX_BATCH_ADDRESSES: 5,
  MAX_BATCH_BALANCE: 20,
  MAX_PAGE_OFFSET: 100,
  MAX_SKIP: 10_000,
  MAX_STATS_LIMIT: 2000,
} as const;
