import { describe, it, expect, beforeEach, afterEach, vi } from "vitest";
import { existsSync, mkdirSync, rmSync, writeFileSync, readFileSync } from "node:fs";
import { join } from "node:path";
import { tmpdir } from "node:os";

const testDir = join(tmpdir(), `echo-test-cleanup-${Date.now()}-${Math.random().toString(36).slice(2)}`);

vi.mock("node:os", async (importOriginal) => {
  const actual = await importOriginal<typeof import("node:os")>();
  return { ...actual, homedir: () => testDir };
});

vi.mock("@utils/logger.js", () => ({
  default: { info: vi.fn(), warn: vi.fn(), debug: vi.fn(), error: vi.fn() },
}));

const { cleanLegacyBashrcAlias } = await import("@utils/legacy-cleanup.js");

const KNOWN_LEGACY_BLOCK = `
# echoclaw alias - loads keystore password from OpenClaw config
echoclaw() {
  export ECHO_KEYSTORE_PASSWORD=""
  command echoclaw "$@"
}
`;

const BASHRC_PATH = join(testDir, ".bashrc");
const ZSHRC_PATH = join(testDir, ".zshrc");

describe("cleanLegacyBashrcAlias", () => {
  beforeEach(() => {
    mkdirSync(testDir, { recursive: true });
  });

  afterEach(() => {
    rmSync(testDir, { recursive: true, force: true });
  });

  it("should remove known legacy block from .bashrc", () => {
    const before = `# other stuff\nexport PATH="/usr/bin"\n${KNOWN_LEGACY_BLOCK}\n# more stuff\nalias ls='ls --color'\n`;
    writeFileSync(BASHRC_PATH, before);

    const result = cleanLegacyBashrcAlias();

    expect(result.found).toContain(BASHRC_PATH);
    expect(result.cleaned).toContain(BASHRC_PATH);
    expect(result.errors).toHaveLength(0);

    const after = readFileSync(BASHRC_PATH, "utf-8");
    expect(after).not.toContain("echoclaw alias");
    expect(after).not.toContain("echoclaw()");
    expect(after).toContain("export PATH");
    expect(after).toContain("alias ls=");
  });

  it("should remove block with 1-3 intermediate lines between comment and function", () => {
    const block = `
# echoclaw alias - loads keystore password
# Generated by echoclaw onboard v1.2.0
# Do not edit manually
echoclaw() {
  export ECHO_KEYSTORE_PASSWORD=""
  command echoclaw "$@"
}
`;
    writeFileSync(BASHRC_PATH, `# header\n${block}\n# footer\n`);

    const result = cleanLegacyBashrcAlias();

    expect(result.cleaned).toContain(BASHRC_PATH);
    const after = readFileSync(BASHRC_PATH, "utf-8");
    expect(after).not.toContain("echoclaw alias");
    expect(after).toContain("# header");
    expect(after).toContain("# footer");
  });

  it("should NOT match block with >3 lines gap between comment and function", () => {
    const block = `
# echoclaw alias
line1
line2
line3
line4
echoclaw() {
  command echoclaw "$@"
}
`;
    writeFileSync(BASHRC_PATH, `# header\n${block}\n# footer\n`);

    const result = cleanLegacyBashrcAlias();

    expect(result.found).toHaveLength(0);
    expect(result.cleaned).toHaveLength(0);
    const after = readFileSync(BASHRC_PATH, "utf-8");
    expect(after).toContain("echoclaw alias");
  });

  it("should not touch file without legacy alias", () => {
    const content = `export PATH="/usr/bin"\nalias git='git --no-pager'\n`;
    writeFileSync(BASHRC_PATH, content);

    const result = cleanLegacyBashrcAlias();

    expect(result.found).toHaveLength(0);
    expect(result.cleaned).toHaveLength(0);
    expect(readFileSync(BASHRC_PATH, "utf-8")).toBe(content);
  });

  it("should not touch unrelated echoclaw references", () => {
    const content = `# install echoclaw\nnpm i -g @echoclaw/echoclaw\nexport ECHO_KEYSTORE_PASSWORD="pw"\n`;
    writeFileSync(BASHRC_PATH, content);

    const result = cleanLegacyBashrcAlias();

    expect(result.found).toHaveLength(0);
    expect(readFileSync(BASHRC_PATH, "utf-8")).toBe(content);
  });

  it("should gracefully skip when no rc files exist", () => {
    // testDir exists but no .bashrc/.zshrc
    const result = cleanLegacyBashrcAlias();

    expect(result.found).toHaveLength(0);
    expect(result.cleaned).toHaveLength(0);
    expect(result.errors).toHaveLength(0);
  });

  it("should be idempotent — second call is a no-op", () => {
    writeFileSync(BASHRC_PATH, `# header\n${KNOWN_LEGACY_BLOCK}\n# footer\n`);

    cleanLegacyBashrcAlias();
    const afterFirst = readFileSync(BASHRC_PATH, "utf-8");

    const result2 = cleanLegacyBashrcAlias();
    const afterSecond = readFileSync(BASHRC_PATH, "utf-8");

    expect(result2.found).toHaveLength(0);
    expect(result2.cleaned).toHaveLength(0);
    expect(afterSecond).toBe(afterFirst);
  });

  it("should handle both .bashrc and .zshrc", () => {
    writeFileSync(BASHRC_PATH, `# before\n${KNOWN_LEGACY_BLOCK}\n# after\n`);
    writeFileSync(ZSHRC_PATH, `# zsh before\n${KNOWN_LEGACY_BLOCK}\n# zsh after\n`);

    const result = cleanLegacyBashrcAlias();

    expect(result.found).toHaveLength(2);
    expect(result.cleaned).toHaveLength(2);
    expect(readFileSync(BASHRC_PATH, "utf-8")).not.toContain("echoclaw()");
    expect(readFileSync(ZSHRC_PATH, "utf-8")).not.toContain("echoclaw()");
  });
});
