/**
 * Production MCP — DB session lifecycle wrapper.
 *
 * Why this file exists: `approval_queue.session_id`, `messages.session_id`
 * and `protocol_executions.session_id` all have FK references to `sessions`.
 * Any tool dispatch path that touches one of these (most internal mutating
 * tools, all protocol executions via capture pipeline) will fail with a
 * foreign key violation if the MCP session id is not registered in the
 * `sessions` table first.
 *
 * The E2E harness (`src/vex-agent/e2e/mcp/tools.ts`) gets away without this
 * because most of its scenarios use read-only knowledge_* and wallet_read
 * paths that never touch FK-referenced columns. The production MCP server
 * exposes the full `wallet_*`, `polymarket_setup`, mutation protocol path
 * etc. — FK enforcement will fire as soon as the agent uses any of those.
 *
 * Lifecycle reflects MCP transport reality:
 *   - stdio: one parent process spawn = one MCP connection = one DB session.
 *     `createMcpSession({transport:"stdio"})` on `connect`, `endMcpSession`
 *     on the transport `onclose`. Crash before close → session row stays
 *     with `ended_at IS NULL` (cleanup follow-up, see plan §1).
 *   - http: stateful Streamable HTTP transport assigns its own MCP session id
 *     via `sessionIdGenerator`. We map it 1:1 to a DB session id of the form
 *     `mcp-http-{nanoid}` on first `initialize`, end on `onclose`. Stateless
 *     HTTP is not supported in v1.
 */

import { randomBytes } from "node:crypto";
import * as sessionsRepo from "@vex-agent/db/repos/sessions.js";
import logger from "@utils/logger.js";

export type McpTransport = "stdio" | "http";

export interface CreateMcpSessionOptions {
  transport: McpTransport;
  /**
   * For HTTP transport, pass the MCP-side session id generated by the
   * Streamable HTTP transport's `sessionIdGenerator`. For stdio, omit this
   * — a fresh nanoid will be minted.
   */
  externalId?: string;
}

const SESSION_SCOPE = "mcp";
const ID_NANO_LEN = 10; // 10 url-safe bytes ≈ 13 base64url chars; collision-resistant for local use

function nanoid(len: number): string {
  return randomBytes(len)
    .toString("base64")
    .replace(/\+/g, "-")
    .replace(/\//g, "_")
    .replace(/=+$/, "")
    .slice(0, Math.ceil((len * 8) / 6));
}

/**
 * Register a new MCP session in the `sessions` table and return its id.
 * Idempotent on the underlying repo (`createSession` uses ON CONFLICT DO
 * NOTHING), so calling twice with the same externalId is safe but pointless.
 */
export async function createMcpSession(opts: CreateMcpSessionOptions): Promise<string> {
  const id =
    opts.transport === "http" && opts.externalId
      ? `mcp-http-${opts.externalId}`
      : `mcp-${opts.transport}-${nanoid(ID_NANO_LEN)}`;

  await sessionsRepo.createSession(id);
  await sessionsRepo.setScope(id, SESSION_SCOPE);
  logger.info("mcp.session.created", { id, transport: opts.transport });
  return id;
}

/**
 * Mark an MCP session as ended (sets `ended_at = NOW()`). Idempotent — calling
 * twice on the same id is a no-op the second time. Errors are logged and
 * swallowed: an MCP server should not crash on disconnect just because the DB
 * is briefly unreachable.
 */
export async function endMcpSession(id: string): Promise<void> {
  try {
    await sessionsRepo.endSession(id);
    logger.info("mcp.session.ended", { id });
  } catch (err) {
    logger.warn("mcp.session.end_failed", {
      id,
      error: err instanceof Error ? err.message : String(err),
    });
  }
}
