/**
 * Session-memories — insert path. `insertPreparedMemory` lands a single chunk
 * using a pre-materialized render; `insertMemories` batches via
 * `prepareMemoryRender` + `insertPreparedMemory` so there is exactly one
 * body/hash materialization path in the repo.
 *
 * Insert path:
 *   - `body_md` is generated by the repo (not the caller) via `renderBodyMd`
 *     so the materialized column never drifts from the structured fields.
 *   - `content_hash = sha256(theme + happened_md + did_md + tried_md)` is
 *     generated before SQL — narrative core only, NOT body_md / outstanding
 *     (see types.ts for rationale).
 *   - Dedup is per (session_id, content_hash) on active rows — same content
 *     in the same session is a no-op insert. Returns `{ inserted, memory }`.
 */

import type { PoolClient } from "pg";

import { getPool, queryOneWith } from "../../client.js";
import { jsonb } from "../../params.js";
import { vectorLiteral } from "../knowledge/types.js";
import { prepareMemoryRender, type PreparedMemoryRender } from "./render.js";
import {
  BODY_MD_SCHEMA_VERSION,
  mapRow,
  toPersistedItem,
  type NewSessionMemory,
  type SessionMemory,
  type SessionMemoryRow,
} from "./types.js";

export interface InsertResult {
  memory: SessionMemory;
  inserted: boolean;
}

/**
 * Insert a single chunk using a pre-materialized render. Track 2 uses this
 * after `prepareMemoryRender` + `embedDocument` to land a row whose
 * `body_md` matches the embedding input verbatim.
 *
 * Existing dedup invariant preserved: `(session_id, content_hash)` partial
 * unique on active rows. Conflicts return the existing row with
 * `inserted: false`.
 */
export async function insertPreparedMemory(
  row: NewSessionMemory,
  prep: PreparedMemoryRender,
  client?: PoolClient,
): Promise<InsertResult> {
  if (row.embedding.length !== row.embeddingDim) {
    throw new Error(
      `insertPreparedMemory: embedding length ${row.embedding.length} does not match embeddingDim ${row.embeddingDim} ` +
        `(session=${row.sessionId}). DB CHECK constraint would reject this.`,
    );
  }

  const exec = client ?? getPool();
  const persistedItems = prep.outstandingItems.map(toPersistedItem);

  // ON CONFLICT DO UPDATE with a no-op SET reliably returns a row whether
  // INSERT or conflict path wins, AND uses postgres' `(xmax = 0)` system-column
  // signal to distinguish freshly-inserted (xmax=0) from conflict-merged rows.
  // This replaces the earlier CTE + UNION ALL fallback, which under concurrent
  // same-hash INSERTs could return zero rows because the conflict's SELECT
  // fallback fired before the winning transaction committed under READ COMMITTED.
  // Codex PR1-PR4 audit P2.2.
  const upserted = await queryOneWith<SessionMemoryRow & { inserted: boolean }>(
    exec,
    `INSERT INTO session_memories (
       session_id, checkpoint_generation,
       theme, theme_source, entities, protocols, error_classes, chains, tasks,
       happened_md, did_md, tried_md, body_md, body_md_schema_version, body_md_hash,
       outstanding_items,
       source_start_message_id, source_end_message_id,
       inference_model,
       importance, confidence,
       embedding, embedding_model, embedding_dim,
       content_hash
     )
     VALUES (
       $1, $2,
       $3, $4, $5, $6, $7, $8, $9,
       $10, $11, $12, $13, $14, $15,
       $16::jsonb,
       $17, $18,
       $19,
       COALESCE($20::int, 5), COALESCE($21::numeric, 0.5),
       $22::vector, $23, $24,
       $25
     )
     ON CONFLICT (session_id, content_hash) WHERE status = 'active'
     DO UPDATE SET updated_at = session_memories.updated_at
     RETURNING *, (xmax = 0) AS inserted`,
    [
      row.sessionId,
      row.checkpointGeneration,
      row.theme,
      row.themeSource,
      row.entities,
      row.protocols,
      row.errorClasses,
      row.chains,
      row.tasks,
      row.happenedMd,
      row.didMd,
      row.triedMd,
      prep.bodyMd,
      BODY_MD_SCHEMA_VERSION,
      prep.bodyMdHash,
      jsonb(persistedItems),
      row.sourceStartMessageId,
      row.sourceEndMessageId,
      row.inferenceModel,
      row.importance ?? null,
      row.confidence ?? null,
      vectorLiteral(row.embedding),
      row.embeddingModel,
      row.embeddingDim,
      prep.contentHash,
    ],
  );
  if (!upserted) {
    throw new Error(`insertPreparedMemory: upsert returned no row for session=${row.sessionId}`);
  }
  const { inserted, ...rest } = upserted;
  return { memory: mapRow(rest as SessionMemoryRow), inserted };
}

/**
 * Batch insert. Delegates to `prepareMemoryRender` + `insertPreparedMemory`
 * per row so there is exactly one body/hash materialization path in the
 * repo (codex PR3-final P1: collapse the previous standalone SQL into the
 * shared pair).
 *
 * Each row's `embedding.length === embeddingDim` is validated upfront so a
 * mismatched batch fails fast before any DB writes.
 *
 * Callers that need byte-identical body_md vs embedding input (Track 2
 * worker) should call `prepareMemoryRender` + `insertPreparedMemory`
 * directly — `insertMemories` is for non-embedding-critical batches where
 * the repo generates outstanding-item UUIDs.
 */
export async function insertMemories(
  rows: readonly NewSessionMemory[],
  client?: PoolClient,
): Promise<InsertResult[]> {
  if (rows.length === 0) return [];

  for (const r of rows) {
    if (r.embedding.length !== r.embeddingDim) {
      throw new Error(
        `insertMemories: embedding length ${r.embedding.length} does not match embeddingDim ${r.embeddingDim} ` +
          `(session=${r.sessionId}). DB CHECK constraint would reject this.`,
      );
    }
  }

  const results: InsertResult[] = [];
  for (const r of rows) {
    const prep = prepareMemoryRender({
      theme: r.theme,
      happenedMd: r.happenedMd,
      didMd: r.didMd,
      triedMd: r.triedMd,
      outstandingTexts: r.outstandingTexts,
    });
    const inserted = await insertPreparedMemory(r, prep, client);
    results.push(inserted);
  }
  return results;
}
