/**
 * Session-memories CRUD — insert (with content_hash dedup), getById,
 * listBySession, count helpers, recent theme listing, and outstanding-item
 * resolution.
 *
 * Insert path:
 *   - `body_md` is generated by the repo (not the caller) via `renderBodyMd`
 *     so the materialized column never drifts from the structured fields.
 *   - `content_hash = sha256(theme + happened_md + did_md + tried_md)` is
 *     generated before SQL — narrative core only, NOT body_md / outstanding
 *     (see types.ts for rationale).
 *   - Dedup is per (session_id, content_hash) on active rows — same content
 *     in the same session is a no-op insert. Returns `{ inserted, memory }`.
 *
 * Resolution path (`markOutstandingResolved`):
 *   - Updates one element of the `outstanding_items` JSONB array by id.
 *   - Re-renders `body_md` from the new state. Caller is responsible for
 *     re-embedding and updating `embedding` + `embedding_model` + dim if the
 *     hash changes substantially; this repo does NOT re-embed on its own
 *     (embedding service IO must be explicit at call sites).
 */

import type { PoolClient } from "pg";

import { execute, getPool, query, queryOne, queryOneWith } from "../../client.js";
import { jsonb } from "../../params.js";
import { vectorLiteral } from "../knowledge/types.js";
import {
  BODY_MD_SCHEMA_VERSION,
  computeBodyMdHash,
  computeContentHash,
  fromPersistedItem,
  MEMORY_COLUMNS,
  mapRow,
  newOutstandingItem,
  renderBodyMd,
  toPersistedItem,
  type NewSessionMemory,
  type OutstandingItem,
  type OutstandingItemPersisted,
  type SessionMemory,
  type SessionMemoryRow,
} from "./types.js";

export interface InsertResult {
  memory: SessionMemory;
  inserted: boolean;
}

/**
 * Materialized chunk render — outstanding items, body_md, and content_hash
 * computed exactly once from the caller's inputs. Track 2 (the chunking
 * worker) calls `prepareMemoryRender` BEFORE embedding so the bytes fed
 * into `embedDocument` are byte-identical to the `body_md` persisted by
 * `insertPreparedMemory` — that pair guarantees the recall-time embedding
 * vector continues to represent what's actually stored in the row.
 *
 * Without this split, the worker would render+embed, then `insertMemories`
 * would generate FRESH `randomUUID()` outstanding items and re-render
 * `body_md`, and the embedding vector would describe a body the DB no
 * longer contains. Codex flagged this as a correctness blocker.
 */
export interface PreparedMemoryRender {
  outstandingItems: readonly OutstandingItem[];
  bodyMd: string;
  bodyMdHash: string;
  contentHash: string;
}

export function prepareMemoryRender(parts: {
  theme: string;
  happenedMd: string;
  didMd: string;
  triedMd: string;
  outstandingTexts: readonly string[];
}): PreparedMemoryRender {
  const outstandingItems: OutstandingItem[] = parts.outstandingTexts.map(newOutstandingItem);
  const bodyMd = renderBodyMd({
    happenedMd: parts.happenedMd,
    didMd: parts.didMd,
    triedMd: parts.triedMd,
    outstandingItems,
  });
  const bodyMdHash = computeBodyMdHash(bodyMd);
  const contentHash = computeContentHash({
    theme: parts.theme,
    happenedMd: parts.happenedMd,
    didMd: parts.didMd,
    triedMd: parts.triedMd,
  });
  return { outstandingItems, bodyMd, bodyMdHash, contentHash };
}

/**
 * Insert a single chunk using a pre-materialized render. Track 2 uses this
 * after `prepareMemoryRender` + `embedDocument` to land a row whose
 * `body_md` matches the embedding input verbatim.
 *
 * Existing dedup invariant preserved: `(session_id, content_hash)` partial
 * unique on active rows. Conflicts return the existing row with
 * `inserted: false`.
 */
export async function insertPreparedMemory(
  row: NewSessionMemory,
  prep: PreparedMemoryRender,
  client?: PoolClient,
): Promise<InsertResult> {
  if (row.embedding.length !== row.embeddingDim) {
    throw new Error(
      `insertPreparedMemory: embedding length ${row.embedding.length} does not match embeddingDim ${row.embeddingDim} ` +
        `(session=${row.sessionId}). DB CHECK constraint would reject this.`,
    );
  }

  const exec = client ?? getPool();
  const persistedItems = prep.outstandingItems.map(toPersistedItem);

  // ON CONFLICT DO UPDATE with a no-op SET reliably returns a row whether
  // INSERT or conflict path wins, AND uses postgres' `(xmax = 0)` system-column
  // signal to distinguish freshly-inserted (xmax=0) from conflict-merged rows.
  // This replaces the earlier CTE + UNION ALL fallback, which under concurrent
  // same-hash INSERTs could return zero rows because the conflict's SELECT
  // fallback fired before the winning transaction committed under READ COMMITTED.
  // Codex PR1-PR4 audit P2.2.
  const upserted = await queryOneWith<SessionMemoryRow & { inserted: boolean }>(
    exec,
    `INSERT INTO session_memories (
       session_id, checkpoint_generation,
       theme, theme_source, entities, protocols, error_classes, chains, tasks,
       happened_md, did_md, tried_md, body_md, body_md_schema_version, body_md_hash,
       outstanding_items,
       source_start_message_id, source_end_message_id,
       inference_model,
       importance, confidence,
       embedding, embedding_model, embedding_dim,
       content_hash
     )
     VALUES (
       $1, $2,
       $3, $4, $5, $6, $7, $8, $9,
       $10, $11, $12, $13, $14, $15,
       $16::jsonb,
       $17, $18,
       $19,
       COALESCE($20::int, 5), COALESCE($21::numeric, 0.5),
       $22::vector, $23, $24,
       $25
     )
     ON CONFLICT (session_id, content_hash) WHERE status = 'active'
     DO UPDATE SET updated_at = session_memories.updated_at
     RETURNING *, (xmax = 0) AS inserted`,
    [
      row.sessionId,
      row.checkpointGeneration,
      row.theme,
      row.themeSource,
      row.entities,
      row.protocols,
      row.errorClasses,
      row.chains,
      row.tasks,
      row.happenedMd,
      row.didMd,
      row.triedMd,
      prep.bodyMd,
      BODY_MD_SCHEMA_VERSION,
      prep.bodyMdHash,
      jsonb(persistedItems),
      row.sourceStartMessageId,
      row.sourceEndMessageId,
      row.inferenceModel,
      row.importance ?? null,
      row.confidence ?? null,
      vectorLiteral(row.embedding),
      row.embeddingModel,
      row.embeddingDim,
      prep.contentHash,
    ],
  );
  if (!upserted) {
    throw new Error(`insertPreparedMemory: upsert returned no row for session=${row.sessionId}`);
  }
  const { inserted, ...rest } = upserted;
  return { memory: mapRow(rest as SessionMemoryRow), inserted };
}

/**
 * Batch insert. Delegates to `prepareMemoryRender` + `insertPreparedMemory`
 * per row so there is exactly one body/hash materialization path in the
 * repo (codex PR3-final P1: collapse the previous standalone SQL into the
 * shared pair).
 *
 * Each row's `embedding.length === embeddingDim` is validated upfront so a
 * mismatched batch fails fast before any DB writes.
 *
 * Callers that need byte-identical body_md vs embedding input (Track 2
 * worker) should call `prepareMemoryRender` + `insertPreparedMemory`
 * directly — `insertMemories` is for non-embedding-critical batches where
 * the repo generates outstanding-item UUIDs.
 */
export async function insertMemories(
  rows: readonly NewSessionMemory[],
  client?: PoolClient,
): Promise<InsertResult[]> {
  if (rows.length === 0) return [];

  for (const r of rows) {
    if (r.embedding.length !== r.embeddingDim) {
      throw new Error(
        `insertMemories: embedding length ${r.embedding.length} does not match embeddingDim ${r.embeddingDim} ` +
          `(session=${r.sessionId}). DB CHECK constraint would reject this.`,
      );
    }
  }

  const results: InsertResult[] = [];
  for (const r of rows) {
    const prep = prepareMemoryRender({
      theme: r.theme,
      happenedMd: r.happenedMd,
      didMd: r.didMd,
      triedMd: r.triedMd,
      outstandingTexts: r.outstandingTexts,
    });
    const inserted = await insertPreparedMemory(r, prep, client);
    results.push(inserted);
  }
  return results;
}

export async function getById(id: number): Promise<SessionMemory | null> {
  if (!Number.isFinite(id) || id <= 0) return null;
  const row = await queryOne<SessionMemoryRow>(
    `SELECT ${MEMORY_COLUMNS} FROM session_memories WHERE id = $1`,
    [id],
  );
  return row ? mapRow(row) : null;
}

export async function listActiveBySession(
  sessionId: string,
  limit = 50,
): Promise<SessionMemory[]> {
  const rows = await query<SessionMemoryRow>(
    `SELECT ${MEMORY_COLUMNS}
     FROM session_memories
     WHERE session_id = $1 AND status = 'active'
     ORDER BY created_at DESC, id DESC
     LIMIT $2`,
    [sessionId, limit],
  );
  return rows.map(mapRow);
}

export interface SessionMemoryStats {
  activeCount: number;
  compactCount: number;
  unresolvedOutstandingCount: number;
  recentThemes: string[];
}

/**
 * One-call summary used by `buildMemoryStateBanner` to render the system
 * prompt banner without N+1 queries.
 *
 * - `activeCount` counts all active rows regardless of outstanding resolution.
 *   Resolved outstanding items do NOT remove the row from the count — the
 *   chunk continues to represent a piece of past narrative.
 * - `compactCount` reads `sessions.checkpoint_generation` directly. A compact
 *   can complete with zero inserted chunks (all rejected by exclusion /
 *   redaction, or Track 2 still in-flight), so deriving compactCount from
 *   MAX(session_memories.checkpoint_generation) would falsely report 0.
 * - `unresolvedOutstandingCount` sums elements where `resolved_at IS NULL`
 *   across all active rows for the session (snake_case JSONB keys per
 *   migration 016).
 * - `recentThemes` lists DISTINCT themes ordered by most recent created_at,
 *   capped by `recentLimit`.
 */
export async function getSessionMemoryStats(
  sessionId: string,
  recentLimit: number,
): Promise<SessionMemoryStats> {
  // Single round-trip CTE — banner is rebuilt every turn.
  const row = await queryOne<{
    active_count: string;
    compact_count: string;
    unresolved_outstanding: string;
    recent_themes: string[] | null;
  }>(
    `WITH active AS (
       SELECT id, theme, created_at, outstanding_items
       FROM session_memories
       WHERE session_id = $1 AND status = 'active'
     ),
     theme_recent AS (
       SELECT theme
       FROM (
         SELECT DISTINCT ON (theme) theme, MAX(created_at) AS last_at
         FROM active
         GROUP BY theme
       ) t
       ORDER BY last_at DESC
       LIMIT $2
     )
     SELECT
       (SELECT COUNT(*)::text FROM active)                                           AS active_count,
       (SELECT COALESCE(checkpoint_generation, 0)::text
          FROM sessions WHERE id = $1)                                               AS compact_count,
       (SELECT COALESCE(SUM(
          (SELECT COUNT(*) FROM jsonb_array_elements(outstanding_items) item
           WHERE item->>'resolved_at' IS NULL)
       ), 0)::text FROM active)                                                      AS unresolved_outstanding,
       (SELECT array_agg(theme) FROM theme_recent)                                   AS recent_themes`,
    [sessionId, recentLimit],
  );

  if (!row) {
    return { activeCount: 0, compactCount: 0, unresolvedOutstandingCount: 0, recentThemes: [] };
  }
  return {
    activeCount: Number.parseInt(row.active_count, 10),
    compactCount: Number.parseInt(row.compact_count, 10),
    unresolvedOutstandingCount: Number.parseInt(row.unresolved_outstanding, 10),
    recentThemes: row.recent_themes ?? [],
  };
}

// ── Outstanding item resolution ─────────────────────────────────

export type ResolveOutstandingResult =
  | { ok: true; memory: SessionMemory }
  | { ok: false; reason: "memory_not_found" | "item_not_found" | "already_resolved" };

/**
 * Resolve a single outstanding item by id. Updates the JSONB array element,
 * re-renders `body_md`, recomputes the row's `updated_at`. Embedding is NOT
 * re-generated here — that requires the embedding service and the caller is
 * responsible (typically the tool handler) for orchestrating that.
 *
 * Concurrency: the read + transform + write runs inside a single
 * transaction with `SELECT ... FOR UPDATE` on the memory row. Two concurrent
 * resolutions race on the lock; the second one re-reads the row's current
 * `outstanding_items` after acquiring it, so a resolution already applied
 * by the first call cleanly returns `already_resolved` rather than
 * silently overwriting the resolution_note. (codex P2 — round 2.)
 */
export async function markOutstandingResolved(
  memoryId: number,
  outstandingItemId: string,
  resolutionNote: string,
  resolutionSource: "agent" | "user" | "auto",
): Promise<ResolveOutstandingResult> {
  const pool = getPool();
  const tx = await pool.connect();
  try {
    await tx.query("BEGIN");

    const lockedRow = await queryOneWith<SessionMemoryRow>(
      tx,
      `SELECT ${MEMORY_COLUMNS} FROM session_memories WHERE id = $1 FOR UPDATE`,
      [memoryId],
    );
    if (!lockedRow) {
      await tx.query("ROLLBACK").catch(() => undefined);
      return { ok: false, reason: "memory_not_found" };
    }
    const existing = mapRow(lockedRow);

    const item = existing.outstandingItems.find((it) => it.id === outstandingItemId);
    if (!item) {
      await tx.query("ROLLBACK").catch(() => undefined);
      return { ok: false, reason: "item_not_found" };
    }
    if (item.resolvedAt !== null) {
      await tx.query("ROLLBACK").catch(() => undefined);
      return { ok: false, reason: "already_resolved" };
    }

    const updatedItems: OutstandingItem[] = existing.outstandingItems.map((it) =>
      it.id === outstandingItemId
        ? {
            ...it,
            resolvedAt: new Date().toISOString(),
            resolutionNote,
            resolutionSource,
          }
        : it,
    );

    const newBodyMd = renderBodyMd({
      happenedMd: existing.happenedMd,
      didMd: existing.didMd,
      triedMd: existing.triedMd,
      outstandingItems: updatedItems,
    });
    const newBodyMdHash = computeBodyMdHash(newBodyMd);

    // Persist via snake_case JSONB (matches migration 016 + unresolved-count
    // SQL). content_hash is NOT updated because the immutable narrative core
    // didn't change (see types.ts content-hash contract). body_md_hash IS
    // updated so a stale `updateEmbedding` call from a concurrent resolution
    // path can be rejected by its WHERE clause (codex PR3-final race fix).
    const persistedItems = updatedItems.map(toPersistedItem);
    const updated = await queryOneWith<SessionMemoryRow>(
      tx,
      `UPDATE session_memories
       SET outstanding_items = $2::jsonb,
           body_md           = $3,
           body_md_hash      = $4,
           updated_at        = NOW()
       WHERE id = $1
       RETURNING ${MEMORY_COLUMNS}`,
      [memoryId, jsonb(persistedItems), newBodyMd, newBodyMdHash],
    );
    await tx.query("COMMIT");
    if (!updated) return { ok: false, reason: "memory_not_found" };
    return { ok: true, memory: mapRow(updated) };
  } catch (err) {
    await tx.query("ROLLBACK").catch(() => undefined);
    throw err;
  } finally {
    tx.release();
  }
}

// ── Maintenance: re-embed after body_md change ──────────────────

/**
 * Update only the embedding columns. Used by the resolution path once the
 * caller has produced a fresh embedding for the new body. Body_md is NOT
 * updated here; call `markOutstandingResolved` first.
 *
 * Race-safety: the UPDATE is conditional on `body_md_hash = $expectedHash`.
 * The caller passes the hash of the body the embedding was computed against
 * (`result.memory.bodyMdHash` from the same `markOutstandingResolved` call).
 * If a concurrent resolution rewrote `body_md` (and bumped its hash) between
 * the embed call and this UPDATE, the WHERE clause excludes the row and the
 * function returns `false` — the embedding was computed against a body that
 * is no longer current, so writing it would leave a stale vector on a fresh
 * body. The losing caller logs `mark_outstanding_resolved.embed_stale`; the
 * winning caller's embedding lands. (codex PR2 round-3 P2 / PR3-final race fix.)
 */
export async function updateEmbedding(
  memoryId: number,
  embedding: number[],
  embeddingModel: string,
  embeddingDim: number,
  expectedBodyMdHash: string,
): Promise<boolean> {
  if (embedding.length !== embeddingDim) {
    throw new Error(
      `updateEmbedding: length ${embedding.length} ≠ dim ${embeddingDim} (memoryId=${memoryId})`,
    );
  }
  const rowCount = await execute(
    `UPDATE session_memories
     SET embedding       = $2::vector,
         embedding_model = $3,
         embedding_dim   = $4,
         updated_at      = NOW()
     WHERE id = $1 AND body_md_hash = $5`,
    [memoryId, vectorLiteral(embedding), embeddingModel, embeddingDim, expectedBodyMdHash],
  );
  return rowCount === 1;
}
