import type { ProtocolToolManifest } from "../types.js";

export const KHALANI_PROTOCOL_TOOLS: readonly ProtocolToolManifest[] = [
  {
    toolId: "khalani.chains.list",
    namespace: "khalani",
    lifecycle: "active",
    description: "List Khalani-supported chains and metadata.",
    mutating: false,
    supportsYes: false,
    commandPath: ["khalani", "chains"],
    params: [
      { key: "refresh", type: "boolean", description: "Refresh in-memory chain cache first.", flag: "--refresh" },
    ],
    exampleParams: {},
    docRefs: ["src/tools/khalani/Khalani.md"],
  },
  {
    toolId: "khalani.tokens.top",
    namespace: "khalani",
    lifecycle: "active",
    description: "List top Khalani tokens, optionally filtered by chain IDs.",
    mutating: false,
    supportsYes: false,
    commandPath: ["khalani", "tokens", "top"],
    params: [
      { key: "chainIds", type: "string", description: "Comma-separated chain IDs or aliases.", flag: "--chain-ids" },
    ],
    exampleParams: { chainIds: "1,solana" },
    docRefs: ["src/tools/khalani/Khalani.md"],
  },
  {
    toolId: "khalani.tokens.search",
    namespace: "khalani",
    lifecycle: "active",
    description: "Search Khalani tokens by symbol, name, or address.",
    mutating: false,
    supportsYes: false,
    commandPath: ["khalani", "tokens", "search"],
    params: [
      { key: "query", type: "string", required: true, description: "Search phrase or token address.", positional: 0 },
      { key: "chainIds", type: "string", description: "Comma-separated chain IDs or aliases.", flag: "--chain-ids" },
    ],
    exampleParams: { query: "USDC", chainIds: "1,8453" },
    docRefs: ["src/tools/khalani/Khalani.md"],
  },
  {
    toolId: "khalani.tokens.autocomplete",
    namespace: "khalani",
    lifecycle: "active",
    description: "Run Khalani semantic token autocomplete.",
    mutating: false,
    supportsYes: false,
    commandPath: ["khalani", "tokens", "autocomplete"],
    params: [
      { key: "keyword", type: "string", required: true, description: "Autocomplete keyword.", positional: 0 },
      { key: "chainIds", type: "string", description: "Comma-separated chain IDs or aliases.", flag: "--chain-ids" },
      { key: "limit", type: "number", description: "Optional result limit.", flag: "--limit" },
    ],
    exampleParams: { keyword: "eth", limit: 5 },
    docRefs: ["src/tools/khalani/Khalani.md"],
  },
  {
    toolId: "khalani.tokens.balances",
    namespace: "khalani",
    lifecycle: "active",
    description: "Get Khalani token balances for an address or configured wallet family.",
    mutating: false,
    supportsYes: false,
    commandPath: ["khalani", "tokens", "balances"],
    params: [
      { key: "address", type: "string", description: "Optional explicit wallet address.", positional: 0 },
      { key: "wallet", type: "string", description: "Configured wallet family fallback: eip155 or solana.", flag: "--wallet" },
      { key: "chainIds", type: "string", description: "Comma-separated chain IDs or aliases.", flag: "--chain-ids" },
    ],
    exampleParams: { wallet: "eip155", chainIds: "1,8453" },
    docRefs: ["src/tools/khalani/Khalani.md"],
  },
  {
    toolId: "khalani.quote.get",
    namespace: "khalani",
    lifecycle: "active",
    description: "Request a read-only Khalani cross-chain quote.",
    mutating: false,
    supportsYes: false,
    commandPath: ["khalani", "quote"],
    params: [
      { key: "fromChain", type: "string", required: true, description: "Source chain ID or alias.", flag: "--from-chain" },
      { key: "fromToken", type: "string", required: true, description: "Source token address.", flag: "--from-token" },
      { key: "toChain", type: "string", required: true, description: "Destination chain ID or alias.", flag: "--to-chain" },
      { key: "toToken", type: "string", required: true, description: "Destination token address.", flag: "--to-token" },
      { key: "amount", type: "string", required: true, description: "Amount in smallest units.", flag: "--amount" },
      { key: "tradeType", type: "string", description: "EXACT_INPUT or EXACT_OUTPUT.", flag: "--trade-type" },
      { key: "fromAddress", type: "string", description: "Optional source wallet override.", flag: "--from-address" },
      { key: "recipient", type: "string", description: "Optional destination recipient override.", flag: "--recipient" },
      { key: "refundTo", type: "string", description: "Optional refund address override.", flag: "--refund-to" },
      { key: "referrer", type: "string", description: "Optional referrer address.", flag: "--referrer" },
      { key: "referrerFeeBps", type: "number", description: "Optional referrer fee in basis points.", flag: "--referrer-fee-bps" },
      { key: "filler", type: "string", description: "Optional filler restriction.", flag: "--filler" },
      { key: "route", type: "string", description: "Optional specific route ID.", flag: "--route" },
      { key: "stream", type: "boolean", description: "Stream NDJSON routes as they arrive.", flag: "--stream" },
      { key: "refreshChains", type: "boolean", description: "Refresh chain metadata first.", flag: "--refresh-chains" },
    ],
    exampleParams: {
      fromChain: "1",
      fromToken: "0xA0b86991c6218b36c1d19d4a2e9eb0ce3606eb48",
      toChain: "solana",
      toToken: "EPjFWdd5AufqSSqeM2qT6fP2J4wR1KjqP7q3QK5r6i7",
      amount: "1000000",
    },
    docRefs: ["src/tools/khalani/Khalani.md"],
  },
  {
    toolId: "khalani.orders.list",
    namespace: "khalani",
    lifecycle: "active",
    description: "List Khalani bridge orders for an address.",
    mutating: false,
    supportsYes: false,
    commandPath: ["khalani", "orders"],
    params: [
      { key: "address", type: "string", description: "Optional explicit wallet address.", positional: 0 },
      { key: "wallet", type: "string", description: "Configured wallet family fallback: eip155 or solana.", flag: "--wallet" },
      { key: "limit", type: "number", description: "Optional result limit.", flag: "--limit" },
      { key: "cursor", type: "number", description: "Optional pagination cursor.", flag: "--cursor" },
      { key: "fromChain", type: "string", description: "Optional source chain filter.", flag: "--from-chain" },
      { key: "toChain", type: "string", description: "Optional destination chain filter.", flag: "--to-chain" },
      { key: "orderIds", type: "string", description: "Optional comma-separated order IDs.", flag: "--order-ids" },
      { key: "txHash", type: "string", description: "Optional transaction hash search.", flag: "--tx-hash" },
    ],
    exampleParams: { wallet: "solana", limit: 20 },
    docRefs: ["src/tools/khalani/Khalani.md"],
  },
  {
    toolId: "khalani.orders.get",
    namespace: "khalani",
    lifecycle: "active",
    description: "Get a single Khalani order by ID.",
    mutating: false,
    supportsYes: false,
    commandPath: ["khalani", "order"],
    params: [
      { key: "orderId", type: "string", required: true, description: "Khalani order ID.", positional: 0 },
    ],
    exampleParams: { orderId: "order_123" },
    docRefs: ["src/tools/khalani/Khalani.md"],
  },
];
